name: Check SQL Assignment 4

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: salesDB
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server mysql-client -y

      - name: Start MySQL and Create Database
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS $DB_DATABASE;" -u$DB_USER -p$DB_PASSWORD

      - name: Load Sample Data
        run: |
          # Check if demo.sql exists before execution
          if [ ! -f ./.github/workflows/demo.sql ]; then
            echo "Missing demo.sql file. Ensure database schema and sample data exist."
            exit 1
          fi

          echo "Executing demo.sql to set up database..."
          sudo mysql -u$DB_USER -p$DB_PASSWORD $DB_DATABASE < ./.github/workflows/demo.sql

      - name: Validate SQL Answers
        run: |
          # Ensure answers.sql is present and not empty
          if [ ! -s ./answers.sql ]; then
            echo "The answers.sql file is missing or empty. Please provide your queries."
            exit 1
          fi

          echo "Executing queries from answers.sql..."
          output=$(mysql -u$DB_USER -p$DB_PASSWORD $DB_DATABASE < ./answers.sql 2>&1)

          # Display the captured output
          echo "Execution Output:"
          echo "$output"

          # Check for SQL errors
          if echo "$output" | grep -q "ERROR"; then
            echo "SQL script execution failed due to errors."
            exit 1
          fi

          echo "All SQL queries executed successfully"
